### ISSUE TITLE
No icons published to npm

### ISSUE THREAD

**Issue by flip-it** [freepik-company/flaticon-uicons#1]
Version 1.7.0 and 1.6.0 doesn't contain any icons on npm. I'm expecting `svg`  and `css` folders to appear after installing, but they are missing. Downgrading to 1.5.0 works fine.

**Comment by SoozaVTW** [comment]
Same issue here. But I can't solve it even downgrading to 1.5.0 :/ there's no svg o css folders.

**Comment by timobech** [comment]
same issue

**Comment by jrmacia-freepik** [comment]
We have removed the svg from the fonts to reduce the weight of the library. In any case, they are available at https://www.flaticon.com/uicons/interface-icons

We will keep the library updated from now on 😉
