### ISSUE TITLE
Package out-of-sync with CDN / Website

### ISSUE THREAD

**Issue by hamilr2** [freepik-company/flaticon-uicons#10]
Hello,

Our editorial team attempted to use a couple of new icons that are available [on the website](https://www.flaticon.com/icon-fonts-most-downloaded), but are not available in the NPM package. For example, `user-gear`.

I was also unable to find a "change log" on the website that indicates what items are new, or when they are added.

We would like to use the package as a way to stay up-to-date, without needing to write some custom build steps that involve downloading files from the CDN.

Will this package be maintained and updated in the future? And somewhat separately, is there a way to subscribe to updates to the UIcons package?

**Comment by DaniFreepik** [comment]
Hello! this package will be maintained in the future, of course! We update it with new icons from time to time. We just updated it right now. The new icons are now available.

**Comment by theolivenbaum** [comment]
@Danizquiano seems like the repo is again out of date - for example artificial-intelligence is missing. Any chance you can update it again?

**Comment by Danizquiano** [comment]
Hello! sorry for the late reply. We are making maintenance improvements to the library. As soon as we have the new version, we will publish it with the updated icons and we will let you know in this channel. Sorry for the inconvenience
