### ISSUE TITLE
Module not found: Can't resolve '@flaticon/flaticon-uicons'

### ISSUE THREAD

**Issue by AbhishekAglave** [freepik-company/flaticon-uicons#11]
I tried both ways to import the package `import "@flaticon/flaticon-uicons";` and `import "~@flaticon/flaticon-uicons/css/all/all";` but it didn't work.
![Screenshot from 2023-04-25 21-17-14](https://user-images.githubusercontent.com/79315357/234332971-ccca7199-8feb-40a2-985b-3a1d7e3419ed.png)

**Comment by DaniFreepik** [comment]
Hi! try removing the import in _app.js and adding this line of code @import "~@flaticon/flaticon-flaticon-uicons/css/all/all"; in the globals.css file. Now if you return inside a component this: <i className='fi fi-rr-user'></i>, you will see the user icon. We recommend that you create a simple icon component to which you can pass the prefix and name properties. 
`export const Icon = ({ prefix, name }) => {
    const className = `fi fi-${prefix}-${name}`;
    return (
        <i className={className}></i>
    )
}`

**Comment by rs-troper** [comment]
I am also fighting this issue. I've scaffolded a basic project using `create-vue`.

Attempting to import the file in my `main.ts` throws an error just like OP.

> try removing the import in _app.js and adding this line of code @import "~@flaticon/flaticon-flaticon-uicons/css/all/all"; in the globals.css file

This does not work either:

```
[plugin:vite:css] [sass] Can't find stylesheet to import.
  ╷
2 │ @import '@flaticon/flaticon-flaticon-uicons/css/all/all';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\theme.scss 2:9      @import
```
