### ISSUE TITLE
The official website Icon class typo

### ISSUE THREAD

**Issue by chosey0** [freepik-company/flaticon-uicons#13]
https://www.flaticon.com/kr/free-icon-font/hand-holding-box_7928244?page=1&position=6&term=%EC%86%90&origin=search&related_id=7928244

The Hand portion of the class on the fi-rrr-hand-holding-box icon is capitalized. It needs to be modified on the official website. I'll leave an issue if I find more typos. :)

**Comment by konchimartin** [comment]
@chosey0 Thank you very much for your valuable advice, we really appreciate the time you took to write to us about this.

This is no longer happening ;)
