### ISSUE TITLE
Lighthouse: "Ensure text remains visible during webfont load"

### ISSUE THREAD

**Issue by XenBG** [freepik-company/flaticon-uicons#14]
You can fix that issue by adding `font-display: swap;` to each of your `@font-face` styles.

![lighthouse](https://github.com/freepik-company/flaticon-uicons/assets/4932709/c3ce50f4-bee6-4f2e-a6e6-b2e3c9c9df53)

Source: https://developer.chrome.com/docs/lighthouse/performance/font-display/

**Comment by konchimartin** [comment]
Hey @XenBG, thank you very much for the suggestion!! 
We will implement it in the next version

**Comment by konchimartin** [comment]
Just added!
