### ISSUE TITLE
Changelog Needed

### ISSUE THREAD

**Issue by XenBG** [freepik-company/flaticon-uicons#18]
When you change the class name of an icon, it's important for the community to be informed about this update. This way, we can promptly make the necessary adjustments in our own projects. That's why having a changelog is essential. A changelog allows us to easily track all the modifications, including new icons introduced in the latest version. This transparency ensures that everyone stays on the same page and can seamlessly integrate these changes into their work.

**Comment by konchimartin** [comment]
Thank you @XenBG very much for your valuable advice, we really appreciate the time you took to write to us about this.
We will take your suggestion into account when assessing what features to introduce next as we continue to improve our website and what we offer.
