### ISSUE TITLE
[Request] More variants of arrow icons

### ISSUE THREAD

**Issue by XenBG** [freepik-company/flaticon-uicons#19]
You already have a diverse range of arrow icons, which is great. However, it's not quite sufficient, as there are still some missing options that we need. We're currently working on a ticketing system and I need various options of arrow icons to use for the priority functionality. Here are some examples from external ticketing system services.

<img width="655" alt="Clipboard - November 3, 2023 10_44 AM" src="https://github.com/freepik-company/flaticon-uicons/assets/4932709/d336f56c-e39e-49fa-a2ac-8e8d73966351">

![Clipboard - November 3, 2023 10_51 AM](https://github.com/freepik-company/flaticon-uicons/assets/4932709/1bab6758-46cc-4dda-bfa8-0940a0e5a931)

**Comment by konchimartin** [comment]
Hello @XenBG, we appreciate your request. We will forward your request to the content creation team for evaluation.

Thank you!
