### ISSUE TITLE
How to import only used icons?

### ISSUE THREAD

**Issue by leoplct** [freepik-company/flaticon-uicons#20]
I have this to include the whole styles

```
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-thin-straight/css/uicons-thin-straight.css'>
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-thin-rounded/css/uicons-thin-rounded.css'>
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
```

but in my code, I only use a few icons like

```
<i class="fi fi-ts-toggle-on" />
<i class="fi-tr-bullseye-arrow" />
<i class="fi-rr-bolt" />
<i class="fi-rr-eye-crossed" />
```

this negatively impacts our performance and lighthouse because we have lots of unused CSS. 
How can I import only a few icons?

![Screenshot 2023-11-09 at 11 07 30](https://github.com/freepik-company/flaticon-uicons/assets/1176145/077eedcb-a4af-4479-a64c-11bca802df20)

**Comment by RohanMishra315** [comment]
hey @leoplct  You can use these code to import only the icons you need and reduce the impact on performance, you can use the `@import` rule in CSS to import specific CSS files for the icons you want to use. 

<style>
  @import url('https://cdn-uicons.flaticon.com/2.0.0/uicons-thin-straight/css/uicons-thin-straight.css');
  @import url('https://cdn-uicons.flaticon.com/2.0.0/uicons-thin-rounded/css/uicons-thin-rounded.css');
</style>

**Comment by konchimartin** [comment]
Hey @leoplct we don't have that functionality at the moment. We may implement it in the future :space_invader: . Thanks for the input :raised_hands: .
