### ISSUE TITLE
Why Thin-rounded Icons Missing?

### ISSUE THREAD

**Issue by djae88** [freepik-company/flaticon-uicons#21]
![image](https://github.com/freepik-company/flaticon-uicons/assets/56290540/75289eb8-2ae6-43a2-a7d2-0978300da32b)
![image](https://github.com/freepik-company/flaticon-uicons/assets/56290540/cde41d5b-0092-4062-80b7-87399c1cfbff)

I found out that the tr-type icon will not be displayed just by installing it with npm i@flaticon/flaticon-uicons
unless the thin-round style is additionally called to cdn.
Now, I use tr-type cdn separately as a temporary measure,
but I wonder why there is no tr-type in the module.
If you have one, but you can't find it,
please let me know

**Comment by konchimartin** [comment]
hi @djae88! currently we don't have the **thin** style icons but they will be coming soon, probably this week it will be available.

Thank you very much for reminding us :)

**Comment by interpromodal-krishna** [comment]
Hi, I also didn't find thin-straight icons in npm package, is it yet to come or available anywhere?

**Comment by konchimartin** [comment]
hi @djae88 @interpromodal-krishna! it is now available. Try it out and if you have any problems let us know :wink:

**Comment by interpromodal-krishna** [comment]
![image](https://github.com/freepik-company/flaticon-uicons/assets/159729724/1e0ce84f-0419-4a30-933b-6d8a9b1c275b)
Where I can get it, I am using version "@flaticon/flaticon-uicons": "^3.1.0", but it is not showing thin icons there in node module, also not loading in project.
fi fi-tr-point-of-sale-bill
fi fi-ts-workflow
fi fi-ts-file-invoice-dollar
fi fi-rr-debt
fi fi-rs-document-paid
fi fi-ss-debt
fi fi-tr-hr-group
fi fi-tr-car-building
fi fi-sr-queue-alt
Please suggest solution...

Thanks,
Krishna Singh

**Comment by konchimartin** [comment]
Hi @interpromodal-krishna try the latest version **3.2.1**, we have just uploaded a fix.

**Comment by interpromodal-krishna** [comment]
Hi, mostly all icons are coming, but still following icon is not coming:
fi fi-rr-revenue

Please suggest solution...

Thanks & Regards,
Krishna Singh

**Comment by konchimartin** [comment]
@interpromodal-krishna yerterday we updated the library with the latest Flaticon icons. Now there must be that icon you were missing :)
