### ISSUE TITLE
shield-trust missing from latest version of the npm package and cdn

### ISSUE THREAD

**Issue by ashleymepham** [freepik-company/flaticon-uicons#24]
The [shield-trust icon](https://www.flaticon.com/free-icon-font/shield-trust_16298305) appears to be missing from the latest cdn and npm package. 

I've tried various combinations of the styles and checked the source css.

**Comment by konchimartin** [comment]
Hi @ashleymepham , we have just updated the library with the latest Flaticon icons.

Enjoy them!
