### ISSUE TITLE
Missing icon 'bell-notification-social-media'

### ISSUE THREAD

**Issue by Gagafeee** [freepik-company/flaticon-uicons#26]
Hi, the icon named 'bell-notification-social-media' exist on the [website](https://www.flaticon.com/free-icon-font/bell-notification-social-media_16309977) but seem to be missing in the library.

Thanks in advance

**Comment by konchimartin** [comment]
Hi @Gagafeee, we have just updated the library with the latest Flaticon icons.

Enjoy them!

**Comment by Gagafeee** [comment]
Thank you for your quick response !
