### ISSUE TITLE
Missing icons on new release + icons with wrong size metrics

### ISSUE THREAD

**Issue by theolivenbaum** [freepik-company/flaticon-uicons#27]
It seems like the [unlock](https://www.flaticon.com/free-icon-font/unlock_3917606?page=1&position=6&term=lock&origin=search&related_id=3917606) icon is missing from the new release.
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/671ebbc0-a932-491b-8527-c07202a3eb9b)

**Comment by theolivenbaum** [comment]
Actually it's quite a few more:

![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/20af572e-b8e8-4abc-aea2-647f737f762f)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/d98bf8aa-eea9-4d44-9ad2-8f0d14313427)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/97579e9b-eb0c-4019-b41c-3eb5eb6b381f)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/91eed5aa-751a-4917-be8e-a2edc1022ec2)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/4ab30fa2-1315-4de7-b92c-1a4ee77eddb0)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/da9609be-1a59-4fa0-bebb-276c40ac0bf4)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/e3971b55-2c12-4619-95a6-869a1f3fd476)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/c4801d2a-59d1-4064-ab81-4ef6db933895)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/b2ec9a68-8abf-4786-9c04-f38581fdaeee)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/90094fca-0d4e-4881-8768-2ccc4f8cb76f)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/bb06ef63-b04d-4d43-a65a-f1ba67eae19f)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/d9fa86e9-4c50-4029-b9c1-92ac61f81533)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/4952ebff-012b-42bf-89bb-5bf007e1638d)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/7ddb1477-20e6-40b6-a8c7-997bf3737eb4)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/92370383-c007-40e5-9614-764cffdf8ddc)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/34cc1081-fda1-4988-a967-e5e7415f057f)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/e7c4f052-660c-476d-b7b8-cb66f51b060d)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/31f9e327-ec1f-4899-a63f-ad063836ba83)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/8277a275-d1f8-49d1-b9a9-49b0bc61f16e)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/53e71169-87d3-4a92-b0a6-23a342a8a8cb)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/cafac0e5-e33d-491b-a4aa-c692a32456fd)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/b521713c-5b8c-484b-aa8e-68fae0386a51)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/8c00eabd-58be-4007-840a-1ddf1b22f9ee)
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/9aefd93b-3d66-4f59-9513-879f620353d2)


There are also some icons with a weird sizing:
![image](https://github.com/freepik-company/flaticon-uicons/assets/8791811/15717f04-49ae-4402-882b-aeba56f96c3a)

**Comment by konchimartin** [comment]
hi @theolivenbaum, thank you very much for reporting :heart_hands: . 
We will correct it as soon as possible :muscle:

**Comment by konchimartin** [comment]
hi @theolivenbaum the problems with the last version have been fixed :sweat_smile: .Try version 3.3.1

**Comment by theolivenbaum** [comment]
Thanks! Rebuilding our UI toolkit now to test it!
