### ISSUE TITLE
It seems broke with next js !

### ISSUE THREAD

**Issue by priyangsubanerjee** [freepik-company/flaticon-uicons#4]
Hi there,

I was trying to use it with next js along with Tailwind css, but wrong icons were rendering every time.

`<i className="fi fi-rr-home mr-2 mt-1"></i>` 

This line of code should render a home icon, but its rendering something else on my screen :)

<img width="118" alt="Screenshot 2022-06-24 at 10 48 37 PM" src="https://user-images.githubusercontent.com/78071484/175610744-4f4f2865-c53d-4fcc-8f6e-1ae12f1b5ed9.png">

*global.css**

<img width="947" alt="Screenshot 2022-06-24 at 10 49 29 PM" src="https://user-images.githubusercontent.com/78071484/175610877-d95d2233-eb2a-4bd7-97e8-3d983fe91818.png">

**Comment by Akshay-Katariya** [comment]
Its not only NextJS whole icons system is broken I guess the mapping is wrong now

**Comment by priyangsubanerjee** [comment]
> Its not only NextJS whole icons system is broken I guess the mapping is wrong now, even I am facing same issue in my project

Seems so !

**Comment by jrmacia-freepik** [comment]
It is fixed in the current version and should display the home icon correctly
