### ISSUE TITLE
All Icon Broke With Different Name

### ISSUE THREAD

**Issue by nyomansunima** [freepik-company/flaticon-uicons#6]
I have tried the icon now and found the icon updated. This caused many problems with the icon and the name do not match each other.

I tried using CDN CSS import. 

I have some ideas to make this become better and more consistent by using the version in each update you're doing. This will keep the version from the previous update

**Comment by jrmacia-freepik** [comment]
We had the problem that you mention but the icon names will no longer be modified and if they do, they will be made on a new version.

Thank you very much for the feedback
