### ISSUE TITLE
Folder "src" include in .npmignore

### ISSUE THREAD

**Issue by yuzu-qroulland** [freepik-company/flaticon-uicons#7]
In version **1.7.0** and probably **1.6.0** there is no **src** folder containing all the assets to use the icons. After checking, this is due to the insertion of the **src** folder in the ._npmignore_. 

>src
esbuild.js
tsconfig.json

It's a pity that this project is not updated anymore because it can be very useful and could compete with fontawesome 😿

In the meantime, you can use version 1.5.0 which seems to work but it would be better if the package was updated 👍🏼

**Comment by jrmacia-freepik** [comment]
We have updated version 1.7.1 recently and released 2.0 with new icons.

The icons used in this library can be found at https://www.flaticon.com/uicons/interface-icons.
