### ISSUE TITLE
Not installing on macos intel

### ISSUE THREAD

**Issue by saurabh-vijayvargiya** [freepik-company/flaticon-uicons#8]
Hi, I am trying to install the package on my macbook pro(intel) running OS ventura. I am getting this error -

```
npm ERR! code 1
npm ERR! path /Users/user_name/sites/projects/ngo/node_modules/@flaticon/flaticon-uicons
npm ERR! command failed
npm ERR! command sh -c -- node license
npm ERR! /Users/user_name/sites/projects/ngo/node_modules/@flaticon/flaticon-uicons/license:1
npm ERR! MIT License
npm ERR!     ^^^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected identifier
npm ERR!     at Object.compileFunction (node:vm:360:18)
npm ERR!     at wrapSafe (node:internal/modules/cjs/loader:1094:15)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1129:27)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:22:47
```
npm -v gives me 8.19.3 and using nodejs v16.19.0

I have tried with nodejs 14, 18 and 19 as well but the same error.

I checked the dependency tab in the npmjs.com and found that [esbuild-linux-64](https://www.npmjs.com/package/esbuild-linux-64) is not installing on macos.

I can see that the package on which this project is dependent is not available for macos, so is there any other workaround so that I am able to use flaticon-uicons in my project? Or is there a plan in the near future ditch that dependency in order to make this package cross-platform?

Thanks

**Comment by EnoahNetzach** [comment]
That's happening to me as well, still on macOS intel, node v18 & yarn v1.22

**Comment by EnoahNetzach** [comment]
@saurabh-vijayvargiya a small workaround if you're using _yarn_ would be to disable building this package in your `package.json` temporarily before installing it, like this:
```json
  "dependenciesMeta": {
    "@flaticon/flaticon-uicons": {
      "built": false
    }
  }
```
Doc on [dependenciesMeta.build](https://yarnpkg.com/configuration/manifest#dependenciesMeta.built).

**Comment by hirani89** [comment]
Hi @EnoahNetzach,

Tried that. Not working.

**Comment by jrmacia-freepik** [comment]
Hi @hirani89,

It is a problem when trying to show the license after installation, while we corrected the error, have you tried to install it in the following way: `npm i @flaticon/flaticon-uicons --ignore-scripts`

**Comment by jrmacia-freepik** [comment]
Hi @hirani89,

Version 2.0.1 should fix the issue

thanks for reporting!
