### ISSUE TITLE
What is the simplest way to find the icon name?

### ISSUE THREAD

**Issue by snake-py** [freepik-company/flaticon-uicons#9]
I am a bit confused, Usually, I would download the icon simply, but I want to use this and reference the icon by class name, but on the flaticon homepage, I do not see the class name for the icon. Where can I find this information?

**Comment by jrmacia-freepik** [comment]
Hi @snake-py ,

In the library [documentation](https://github.com/freepik-company/flaticon-uicons/blob/main/README.md) you can find a way to use it.

If you need how to use a specific icon, look for it on [flaticon.com](https://www.flaticon.com/) and you can find it in the detail of it

![image](https://user-images.githubusercontent.com/121159388/222064983-ee574825-f579-4dfd-8130-4121b976a69e.png)

**Comment by jrmacia-freepik** [comment]
You can find interface icons [here](https://www.flaticon.com/uicons/interface-icons)

**Comment by snake-py** [comment]
@jrmacia-freepik sorry for this dump issue, I was quite confused about that thank you for pointing me to the link. Is the link in the docs? Maybe it would be useful to mention it somewhere - or was I just blind?
